### ISSUE TITLE
espeakup don't work on arch after fresh install

### ISSUE THREAD

**Issue by Adriorjalesvidal** [williamh/espeakup#23]
Hi
I have installed Archlinux about 2 months ago without any problem, but today I've installed 4 times the system with the latest build abailable 2021.06.01, and there is a big problem with the speech output. 
When I have installed the system, I reboot into the newly created arch. I run espeakup, and the voice begins to talk, but when I try to read the previous, next, or actual line, character or word, When the voice starts to speak, it cuts out after a few milliseconds. 
The speaker is working properly, I have tested it on Windows, and using speaker-test command on linux, and run without problems.
The software that is installed is the following

base, linux, linux-firmware, espeakup, alsa-utils, brltty

After pacstrap, I've only installed grub and nano.

I've tested it aswell with pulseaudio, and with the linux-lts, but all results were the same.

I don't find where is the break point, but when the voice must talk, it only says a few milliseconds of sound.

Brltty braille output works properly

Thanks

**Comment by sthibaul** [comment]
Hello,

Could you try to downgrade your alsalibs to version 1.2.4? It was reported on the speakup mailing list that it seems that alsalibs 1.2.5 breaks the espeak output. Alternatively you can try to make espeakup use espeak-ng, apparently it does work fine.

**Comment by Adriorjalesvidal** [comment]
Thanks, I will try the alsa downgrade, 
How can I force espeakup to use espeak-ng?

**Comment by sthibaul** [comment]
> How can I force espeakup to use espeak-ng?

I don't know how that works on arch

**Comment by alex19EP** [comment]
yep. I aware of this problem. as a quick fix you can use my [pkgbuild](https://github.com/alex19EP/pkgbuilds/blob/master/espeakup-git/PKGBUILD)

FYI @dvzrv

**Comment by alex19EP** [comment]
@sthibaul did you receive my email yesterday?

**Comment by sthibaul** [comment]
@alex19EP I don't seem to have received it

**Comment by Adriorjalesvidal** [comment]
@alex19EP  when i launch makepkg appears the following
error: cannot find the fakeroot binary
Error: cannot find the strip binary required for object file tripping
Thanks in advance for your help

**Comment by sthibaul** [comment]
@Adriorjalesvidal so it looks like you just need to install the packages for the fakeroot and strip commands? (for strip it's probably named binutils)

**Comment by alex19EP** [comment]
> when i launch makepkg appears the following

ok when you [compile packages](https://wiki.archlinux.org/title/Arch_User_Repository#Prerequisites) on arch linux from source you need to install the base-devel group.
`pacman -S --needed base-devel`
then
```bash
git clone https://github.com/alex19EP/pkgbuilds.git
cd pkgbuilds/espeakup-git
makepkg -si
```

**Comment by Adriorjalesvidal** [comment]
Thanks. 
I've installed the software, but it doesn't work. When I run systemctl status espeakup, it says that is active inactive (dead).

**Comment by alex19EP** [comment]
> Thanks.
> I've installed the software, but it doesn't work. When I run systemctl status espeakup, it says that is active inactive (dead).

hm can you try `systemctl restart espeakup.service`
and give output of `systemctl status espeakup.service`

**Comment by Adriorjalesvidal** [comment]
Now it worked, I have run systemctl restart espeakup and it started working, and also run systemctl enable espeakup and it runs at startup. All OK, than you so much for your help!
